version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: studybuddy
      POSTGRES_USER: sbuser
      POSTGRES_PASSWORD: sbpass
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: